### ISSUE TITLE
Error on gulp build

### ISSUE THREAD

**Issue by nmeegama** [joni2back/angular-filemanager#191]
Hi I m  getting the following error when i do a gulp build

[17:55:24] Using gulpfile ~/work_repo/angular/ceb/angular-filemanager/gulpfile.js
[17:55:24] Starting 'clean'...
[17:55:24] Starting 'lint'...
[17:55:24] Starting 'cache-templates'...
[17:55:24] Starting 'minify-css'...
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

TypeError: Path must be a string. Received [ '/Users/nmeegama/work_repo/angular/ceb/angular-filemanager/src/templates/current-folder-breadcrumb.html' ]
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at gulp.src.pipe.templateCache.base (/Users/nmeegama/work_repo/angular/ceb/angular-filemanager/gulpfile.js:29:37)
    at templateCacheFile (/Users/nmeegama/work_repo/angular/ceb/angular-filemanager/node_modules/gulp-angular-templatecache/index.js:62:29)
    at wrappedMapper (/Users/nmeegama/work_repo/angular/ceb/angular-filemanager/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (/Users/nmeegama/work_repo/angular/ceb/angular-filemanager/node_modules/map-stream/index.js:96:21)
    at Stream.method [as write] (/Users/nmeegama/work_repo/angular/ceb/angular-filemanager/node_modules/duplexer/index.js:47:39)
    at write (/Users/nmeegama/work_repo/angular/ceb/angular-filemanager/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/nmeegama/work_repo/angular/ceb/angular-filemanager/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/nmeegama/work_repo/angular/ceb/angular-filemanager/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)

<img width="367" alt="screen shot 2016-08-25 at 6 08 55 pm" src="https://cloud.githubusercontent.com/assets/1736109/17969291/08736f0a-6aef-11e6-9c22-62d75bd899a0.png">

The problem is with the cache-templates gulp task

**Comment by nmeegama** [comment]
Changed cache-templates gulp task code
return tplPath + '/' + path.basename(file.history);

to

return tplPath + '/' + path.basename(file.history[0]);

and its working

**Comment by joni2back** [comment]
Hi @nmeegama seems it is a version problem. I will updating npm modules soon
