### ISSUE TITLE
 rights=drwxrwxrwt chmod parse error

### ISSUE THREAD

**Issue by kernel164** [joni2back/angular-filemanager#86]
Thanks for angular-filemanager. I was looking for a better file manager and finally found one.

I'm trying golang backend for angular-filemanager - https://github.com/kernel164/gofe

I get this error if rights=drwxrwxrwt
```
Error: Invalid chmod input data
    at new e (http://localhost:4000/static/angular-filemanager.min.js:1:5013)
    at new l (http://localhost:4000/static/angular-filemanager.min.js:1:6860)
    at http://localhost:4000/static/angular-filemanager.min.js:1:25201
    at Array.map (native)
    at http://localhost:4000/static/angular-filemanager.min.js:1:25178
    at http://localhost:4000/static/angular/angular.min.js:112:182
    at m.$eval (http://localhost:4000/static/angular/angular.min.js:126:250)
    at m.$digest (http://localhost:4000/static/angular/angular.min.js:123:365)
    at m.$apply (http://localhost:4000/static/angular/angular.min.js:127:12)
    at l (http://localhost:4000/static/angular/angular.min.js:81:327)
```

**Comment by joni2back** [comment]
You are using item with [sticky bit](https://en.wikipedia.org/wiki/Sticky_bit), let me check if can support this...

**Comment by joni2back** [comment]
Fixed, sticky-bit prop is converted to execute property. Maybe not the best resolution, but necessary to dont broke the app.
